[package]
name = "rays"
version = "1.0.0"
authors = ["Markus W. <m@rkus.online>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
rayon = "1.0.3"
lodepng = "2.4.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.0"
clap = "2.32.0"