[package]
name = "rays"
version = "1.0.0"
authors = ["Markus Webel <markuswebel@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }
rayon = "1.0.3"
lodepng = "3.7"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.0"
clap = "3.2"
