[[material]]
name = "full-diffuse"
reflection = { center = 1.0, edges = 1.0, power = 1.0, max_angle = 90.0 }

[[material]]
name = "gray"
color = [0.5, 0.5, 0.5]

[[material]]
name = "orange"
color = [1.0, 0.6, 0.1]

[[material]]
name = "blue"
color = [0.25, 0.75, 1.0]

[[obj-sphere]]
uv-mapper = "full-diffuse"
origin = [0.0, 7.5, 11.0]
radius = 4.5

[[obj-infinite-plane]]
uv-mapper = "full-diffuse"

[[obj-infinite-plane]]
uv-mapper = "full-diffuse"
origin = [0.0, 15.0, 0.0]
rotation = [180.0, 0.0, 0.0]

[[obj-infinite-plane]]
uv-mapper = "gray"
origin = [0.0, 0.0, 20.0]
rotation = [-90.0, 0.0, 0.0]

[[obj-infinite-plane]]
uv-mapper = "orange"
origin = [-15.0, 0.0, 0.0]
rotation = [90.0, 90.0, 0.0]

[[obj-infinite-plane]]
uv-mapper = "blue"
origin = [15.0, 0.0, 0.0]
rotation = [90.0, -90.0, 0.0]

[[camera]]
position = [0.0, 7.5, -10.0]
fov_h = 40.0

[[render-params]]
ao.strength = 0.4
ao.distance = 5.0